// GERADO — não edite à mão.
//
// Fonte: tabela CEP→mesorregião do IBGE, a mesma que o `svc-analysis-bi` usava
// em `configs/ibge_mesoregions.csv`. Regenerar com:
//   python3 scripts/gen-ibge-table.py
//
// Por que a tabela mora AQUI e não no BI (ADR de generalização na origem):
// o `svc-analysis-bi` promete não receber PII, e CEP é PII. Para cumprir a
// promessa no código — e não só no documento — a generalização acontece na
// origem: o social resolve CEP→mesorregião e publica só a mesorregião.

/// Mesorregião do IBGE — a menor granularidade geográfica que sai deste serviço.
public struct Mesoregion: Codable, Equatable, Hashable, Sendable {
    public let code: String
    public let name: String
    public let stateCode: String
    public let stateName: String
    public let region: String

    public init(code: String, name: String, stateCode: String, stateName: String, region: String) {
        self.code = code
        self.name = name
        self.stateCode = stateCode
        self.stateName = stateName
        self.region = region
    }
}

enum IBGEMesoregionTable {
    /// Faixas de CEP, ORDENADAS por início.
    ///
    /// A fonte do IBGE lista o CEP **inicial** de cada faixa (01000, 02000,
    /// 28600, 29100…), não prefixos exatos. Uma faixa vale até o início da
    /// seguinte, então a resolução é "a maior faixa <= o CEP consultado" —
    /// nunca casamento de prefixo. Buscar por prefixo faria 01310100
    /// (Av. Paulista) não resolver nada, porque `01310` não está na tabela.
    static let ranges: [(start: String, meso: Mesoregion)] = [
        (start: "01000", meso: Mesoregion(code: "3550", name: "Metropolitana de Sao Paulo", stateCode: "35", stateName: "Sao Paulo", region: "Sudeste")),
        (start: "02000", meso: Mesoregion(code: "3550", name: "Metropolitana de Sao Paulo", stateCode: "35", stateName: "Sao Paulo", region: "Sudeste")),
        (start: "03000", meso: Mesoregion(code: "3550", name: "Metropolitana de Sao Paulo", stateCode: "35", stateName: "Sao Paulo", region: "Sudeste")),
        (start: "04000", meso: Mesoregion(code: "3550", name: "Metropolitana de Sao Paulo", stateCode: "35", stateName: "Sao Paulo", region: "Sudeste")),
        (start: "05000", meso: Mesoregion(code: "3550", name: "Metropolitana de Sao Paulo", stateCode: "35", stateName: "Sao Paulo", region: "Sudeste")),
        (start: "06000", meso: Mesoregion(code: "3550", name: "Metropolitana de Sao Paulo", stateCode: "35", stateName: "Sao Paulo", region: "Sudeste")),
        (start: "07000", meso: Mesoregion(code: "3550", name: "Metropolitana de Sao Paulo", stateCode: "35", stateName: "Sao Paulo", region: "Sudeste")),
        (start: "08000", meso: Mesoregion(code: "3550", name: "Metropolitana de Sao Paulo", stateCode: "35", stateName: "Sao Paulo", region: "Sudeste")),
        (start: "09000", meso: Mesoregion(code: "3550", name: "Metropolitana de Sao Paulo", stateCode: "35", stateName: "Sao Paulo", region: "Sudeste")),
        (start: "10000", meso: Mesoregion(code: "3548", name: "Macro Metropolitana Paulista", stateCode: "35", stateName: "Sao Paulo", region: "Sudeste")),
        (start: "11000", meso: Mesoregion(code: "3549", name: "Litoral Sul Paulista", stateCode: "35", stateName: "Sao Paulo", region: "Sudeste")),
        (start: "12000", meso: Mesoregion(code: "3541", name: "Vale do Paraiba Paulista", stateCode: "35", stateName: "Sao Paulo", region: "Sudeste")),
        (start: "13000", meso: Mesoregion(code: "3548", name: "Macro Metropolitana Paulista", stateCode: "35", stateName: "Sao Paulo", region: "Sudeste")),
        (start: "14000", meso: Mesoregion(code: "3543", name: "Ribeirao Preto", stateCode: "35", stateName: "Sao Paulo", region: "Sudeste")),
        (start: "15000", meso: Mesoregion(code: "3544", name: "Aracatuba", stateCode: "35", stateName: "Sao Paulo", region: "Sudeste")),
        (start: "16000", meso: Mesoregion(code: "3545", name: "Sao Jose do Rio Preto", stateCode: "35", stateName: "Sao Paulo", region: "Sudeste")),
        (start: "17000", meso: Mesoregion(code: "3546", name: "Marilia", stateCode: "35", stateName: "Sao Paulo", region: "Sudeste")),
        (start: "18000", meso: Mesoregion(code: "3547", name: "Itapetininga", stateCode: "35", stateName: "Sao Paulo", region: "Sudeste")),
        (start: "19000", meso: Mesoregion(code: "3542", name: "Piracicaba", stateCode: "35", stateName: "Sao Paulo", region: "Sudeste")),
        (start: "20000", meso: Mesoregion(code: "3301", name: "Metropolitana do Rio de Janeiro", stateCode: "33", stateName: "Rio de Janeiro", region: "Sudeste")),
        (start: "21000", meso: Mesoregion(code: "3301", name: "Metropolitana do Rio de Janeiro", stateCode: "33", stateName: "Rio de Janeiro", region: "Sudeste")),
        (start: "22000", meso: Mesoregion(code: "3301", name: "Metropolitana do Rio de Janeiro", stateCode: "33", stateName: "Rio de Janeiro", region: "Sudeste")),
        (start: "23000", meso: Mesoregion(code: "3301", name: "Metropolitana do Rio de Janeiro", stateCode: "33", stateName: "Rio de Janeiro", region: "Sudeste")),
        (start: "24000", meso: Mesoregion(code: "3301", name: "Metropolitana do Rio de Janeiro", stateCode: "33", stateName: "Rio de Janeiro", region: "Sudeste")),
        (start: "25000", meso: Mesoregion(code: "3302", name: "Noroeste Fluminense", stateCode: "33", stateName: "Rio de Janeiro", region: "Sudeste")),
        (start: "26000", meso: Mesoregion(code: "3303", name: "Norte Fluminense", stateCode: "33", stateName: "Rio de Janeiro", region: "Sudeste")),
        (start: "27000", meso: Mesoregion(code: "3304", name: "Centro Fluminense", stateCode: "33", stateName: "Rio de Janeiro", region: "Sudeste")),
        (start: "28000", meso: Mesoregion(code: "3305", name: "Baixadas", stateCode: "33", stateName: "Rio de Janeiro", region: "Sudeste")),
        (start: "28600", meso: Mesoregion(code: "3306", name: "Sul Fluminense", stateCode: "33", stateName: "Rio de Janeiro", region: "Sudeste")),
        (start: "29000", meso: Mesoregion(code: "3201", name: "Noroeste Espírito-santense", stateCode: "32", stateName: "Espirito Santo", region: "Sudeste")),
        (start: "29100", meso: Mesoregion(code: "3202", name: "Litoral Norte Espírito-santense", stateCode: "32", stateName: "Espirito Santo", region: "Sudeste")),
        (start: "29200", meso: Mesoregion(code: "3203", name: "Central Espírito-santense", stateCode: "32", stateName: "Espirito Santo", region: "Sudeste")),
        (start: "29300", meso: Mesoregion(code: "3204", name: "Sul Espírito-santense", stateCode: "32", stateName: "Espirito Santo", region: "Sudeste")),
        (start: "29500", meso: Mesoregion(code: "3203", name: "Central Espírito-santense", stateCode: "32", stateName: "Espirito Santo", region: "Sudeste")),
        (start: "29700", meso: Mesoregion(code: "3203", name: "Central Espírito-santense", stateCode: "32", stateName: "Espirito Santo", region: "Sudeste")),
        (start: "29900", meso: Mesoregion(code: "3204", name: "Sul Espírito-santense", stateCode: "32", stateName: "Espirito Santo", region: "Sudeste")),
        (start: "30000", meso: Mesoregion(code: "3107", name: "Metropolitana de Belo Horizonte", stateCode: "31", stateName: "Minas Gerais", region: "Sudeste")),
        (start: "31000", meso: Mesoregion(code: "3107", name: "Metropolitana de Belo Horizonte", stateCode: "31", stateName: "Minas Gerais", region: "Sudeste")),
        (start: "32000", meso: Mesoregion(code: "3107", name: "Metropolitana de Belo Horizonte", stateCode: "31", stateName: "Minas Gerais", region: "Sudeste")),
        (start: "33000", meso: Mesoregion(code: "3102", name: "Norte de Minas", stateCode: "31", stateName: "Minas Gerais", region: "Sudeste")),
        (start: "34000", meso: Mesoregion(code: "3103", name: "Jequitinhonha", stateCode: "31", stateName: "Minas Gerais", region: "Sudeste")),
        (start: "35000", meso: Mesoregion(code: "3101", name: "Noroeste de Minas", stateCode: "31", stateName: "Minas Gerais", region: "Sudeste")),
        (start: "36000", meso: Mesoregion(code: "3108", name: "Zona da Mata", stateCode: "31", stateName: "Minas Gerais", region: "Sudeste")),
        (start: "37000", meso: Mesoregion(code: "3109", name: "Sul/Sudoeste de Minas", stateCode: "31", stateName: "Minas Gerais", region: "Sudeste")),
        (start: "38000", meso: Mesoregion(code: "3105", name: "Triangulo Mineiro/Alto Paranaiba", stateCode: "31", stateName: "Minas Gerais", region: "Sudeste")),
        (start: "39000", meso: Mesoregion(code: "3104", name: "Vale do Mucuri", stateCode: "31", stateName: "Minas Gerais", region: "Sudeste")),
        (start: "39500", meso: Mesoregion(code: "3106", name: "Central Mineira", stateCode: "31", stateName: "Minas Gerais", region: "Sudeste")),
        (start: "39800", meso: Mesoregion(code: "3110", name: "Campo das Vertentes", stateCode: "31", stateName: "Minas Gerais", region: "Sudeste")),
        (start: "39900", meso: Mesoregion(code: "3111", name: "Oeste de Minas", stateCode: "31", stateName: "Minas Gerais", region: "Sudeste")),
        (start: "39950", meso: Mesoregion(code: "3112", name: "Vale do Rio Doce", stateCode: "31", stateName: "Minas Gerais", region: "Sudeste")),
        (start: "40000", meso: Mesoregion(code: "2904", name: "Metropolitana de Salvador", stateCode: "29", stateName: "Bahia", region: "Nordeste")),
        (start: "41000", meso: Mesoregion(code: "2904", name: "Metropolitana de Salvador", stateCode: "29", stateName: "Bahia", region: "Nordeste")),
        (start: "42000", meso: Mesoregion(code: "2904", name: "Metropolitana de Salvador", stateCode: "29", stateName: "Bahia", region: "Nordeste")),
        (start: "43000", meso: Mesoregion(code: "2903", name: "Centro Sul Baiano", stateCode: "29", stateName: "Bahia", region: "Nordeste")),
        (start: "44000", meso: Mesoregion(code: "2901", name: "Extremo Oeste Baiano", stateCode: "29", stateName: "Bahia", region: "Nordeste")),
        (start: "45000", meso: Mesoregion(code: "2905", name: "Sul Baiano", stateCode: "29", stateName: "Bahia", region: "Nordeste")),
        (start: "46000", meso: Mesoregion(code: "2902", name: "Vale Sao-Franciscano da Bahia", stateCode: "29", stateName: "Bahia", region: "Nordeste")),
        (start: "47000", meso: Mesoregion(code: "2906", name: "Centro Norte Baiano", stateCode: "29", stateName: "Bahia", region: "Nordeste")),
        (start: "48000", meso: Mesoregion(code: "2907", name: "Nordeste Baiano", stateCode: "29", stateName: "Bahia", region: "Nordeste")),
        (start: "49000", meso: Mesoregion(code: "2801", name: "Leste Sergipano", stateCode: "28", stateName: "Sergipe", region: "Nordeste")),
        (start: "49100", meso: Mesoregion(code: "2802", name: "Agreste Sergipano", stateCode: "28", stateName: "Sergipe", region: "Nordeste")),
        (start: "49400", meso: Mesoregion(code: "2803", name: "Sertao Sergipano", stateCode: "28", stateName: "Sergipe", region: "Nordeste")),
        (start: "50000", meso: Mesoregion(code: "2603", name: "Metropolitana de Recife", stateCode: "26", stateName: "Pernambuco", region: "Nordeste")),
        (start: "51000", meso: Mesoregion(code: "2603", name: "Metropolitana de Recife", stateCode: "26", stateName: "Pernambuco", region: "Nordeste")),
        (start: "52000", meso: Mesoregion(code: "2603", name: "Metropolitana de Recife", stateCode: "26", stateName: "Pernambuco", region: "Nordeste")),
        (start: "53000", meso: Mesoregion(code: "2603", name: "Metropolitana de Recife", stateCode: "26", stateName: "Pernambuco", region: "Nordeste")),
        (start: "54000", meso: Mesoregion(code: "2603", name: "Metropolitana de Recife", stateCode: "26", stateName: "Pernambuco", region: "Nordeste")),
        (start: "55000", meso: Mesoregion(code: "2604", name: "Agreste Pernambucano", stateCode: "26", stateName: "Pernambuco", region: "Nordeste")),
        (start: "56000", meso: Mesoregion(code: "2605", name: "Sao Francisco Pernambucano", stateCode: "26", stateName: "Pernambuco", region: "Nordeste")),
        (start: "56300", meso: Mesoregion(code: "2601", name: "Sertao Pernambucano", stateCode: "26", stateName: "Pernambuco", region: "Nordeste")),
        (start: "56500", meso: Mesoregion(code: "2602", name: "Mata Pernambucana", stateCode: "26", stateName: "Pernambuco", region: "Nordeste")),
        (start: "57000", meso: Mesoregion(code: "2701", name: "Sertao Alagoano", stateCode: "27", stateName: "Alagoas", region: "Nordeste")),
        (start: "57100", meso: Mesoregion(code: "2702", name: "Agreste Alagoano", stateCode: "27", stateName: "Alagoas", region: "Nordeste")),
        (start: "57300", meso: Mesoregion(code: "2703", name: "Leste Alagoano", stateCode: "27", stateName: "Alagoas", region: "Nordeste")),
        (start: "57600", meso: Mesoregion(code: "2703", name: "Leste Alagoano", stateCode: "27", stateName: "Alagoas", region: "Nordeste")),
        (start: "58000", meso: Mesoregion(code: "2501", name: "Sertao Paraibano", stateCode: "25", stateName: "Paraiba", region: "Nordeste")),
        (start: "58100", meso: Mesoregion(code: "2502", name: "Borborema", stateCode: "25", stateName: "Paraiba", region: "Nordeste")),
        (start: "58300", meso: Mesoregion(code: "2503", name: "Agreste Paraibano", stateCode: "25", stateName: "Paraiba", region: "Nordeste")),
        (start: "58400", meso: Mesoregion(code: "2504", name: "Mata Paraibana", stateCode: "25", stateName: "Paraiba", region: "Nordeste")),
        (start: "59000", meso: Mesoregion(code: "2401", name: "Oeste Potiguar", stateCode: "24", stateName: "Rio Grande do Norte", region: "Nordeste")),
        (start: "59100", meso: Mesoregion(code: "2402", name: "Central Potiguar", stateCode: "24", stateName: "Rio Grande do Norte", region: "Nordeste")),
        (start: "59300", meso: Mesoregion(code: "2403", name: "Agreste Potiguar", stateCode: "24", stateName: "Rio Grande do Norte", region: "Nordeste")),
        (start: "59600", meso: Mesoregion(code: "2404", name: "Leste Potiguar", stateCode: "24", stateName: "Rio Grande do Norte", region: "Nordeste")),
        (start: "60000", meso: Mesoregion(code: "2303", name: "Metropolitana de Fortaleza", stateCode: "23", stateName: "Ceara", region: "Nordeste")),
        (start: "61000", meso: Mesoregion(code: "2303", name: "Metropolitana de Fortaleza", stateCode: "23", stateName: "Ceara", region: "Nordeste")),
        (start: "62000", meso: Mesoregion(code: "2301", name: "Noroeste Cearense", stateCode: "23", stateName: "Ceara", region: "Nordeste")),
        (start: "62500", meso: Mesoregion(code: "2304", name: "Centro-Sul Cearense", stateCode: "23", stateName: "Ceara", region: "Nordeste")),
        (start: "63000", meso: Mesoregion(code: "2302", name: "Norte Cearense", stateCode: "23", stateName: "Ceara", region: "Nordeste")),
        (start: "63100", meso: Mesoregion(code: "2305", name: "Jaguaribe", stateCode: "23", stateName: "Ceara", region: "Nordeste")),
        (start: "63400", meso: Mesoregion(code: "2306", name: "Sul Cearense", stateCode: "23", stateName: "Ceara", region: "Nordeste")),
        (start: "63500", meso: Mesoregion(code: "2307", name: "Sertoes Cearenses", stateCode: "23", stateName: "Ceara", region: "Nordeste")),
        (start: "64000", meso: Mesoregion(code: "2201", name: "Norte Piauiense", stateCode: "22", stateName: "Piaui", region: "Nordeste")),
        (start: "64100", meso: Mesoregion(code: "2202", name: "Centro-Norte Piauiense", stateCode: "22", stateName: "Piaui", region: "Nordeste")),
        (start: "64400", meso: Mesoregion(code: "2203", name: "Sudoeste Piauiense", stateCode: "22", stateName: "Piaui", region: "Nordeste")),
        (start: "64700", meso: Mesoregion(code: "2204", name: "Sudeste Piauiense", stateCode: "22", stateName: "Piaui", region: "Nordeste")),
        (start: "65000", meso: Mesoregion(code: "2102", name: "Norte Maranhense", stateCode: "21", stateName: "Maranhao", region: "Nordeste")),
        (start: "65100", meso: Mesoregion(code: "2102", name: "Norte Maranhense", stateCode: "21", stateName: "Maranhao", region: "Nordeste")),
        (start: "65400", meso: Mesoregion(code: "2101", name: "Oeste Maranhense", stateCode: "21", stateName: "Maranhao", region: "Nordeste")),
        (start: "65600", meso: Mesoregion(code: "2103", name: "Centro Maranhense", stateCode: "21", stateName: "Maranhao", region: "Nordeste")),
        (start: "65700", meso: Mesoregion(code: "2104", name: "Leste Maranhense", stateCode: "21", stateName: "Maranhao", region: "Nordeste")),
        (start: "65900", meso: Mesoregion(code: "2105", name: "Sul Maranhense", stateCode: "21", stateName: "Maranhao", region: "Nordeste")),
        (start: "66000", meso: Mesoregion(code: "1501", name: "Baixo Amazonas", stateCode: "15", stateName: "Para", region: "Norte")),
        (start: "66100", meso: Mesoregion(code: "1502", name: "Metropolitana de Belem", stateCode: "15", stateName: "Para", region: "Norte")),
        (start: "66500", meso: Mesoregion(code: "1502", name: "Metropolitana de Belem", stateCode: "15", stateName: "Para", region: "Norte")),
        (start: "66800", meso: Mesoregion(code: "1503", name: "Nordeste Paraense", stateCode: "15", stateName: "Para", region: "Norte")),
        (start: "67000", meso: Mesoregion(code: "1502", name: "Metropolitana de Belem", stateCode: "15", stateName: "Para", region: "Norte")),
        (start: "67100", meso: Mesoregion(code: "1504", name: "Sudoeste Paraense", stateCode: "15", stateName: "Para", region: "Norte")),
        (start: "67500", meso: Mesoregion(code: "1505", name: "Sudeste Paraense", stateCode: "15", stateName: "Para", region: "Norte")),
        (start: "67600", meso: Mesoregion(code: "1506", name: "Marajo", stateCode: "15", stateName: "Para", region: "Norte")),
        (start: "68000", meso: Mesoregion(code: "1504", name: "Sudoeste Paraense", stateCode: "15", stateName: "Para", region: "Norte")),
        (start: "68100", meso: Mesoregion(code: "1505", name: "Sudeste Paraense", stateCode: "15", stateName: "Para", region: "Norte")),
        (start: "68300", meso: Mesoregion(code: "1503", name: "Nordeste Paraense", stateCode: "15", stateName: "Para", region: "Norte")),
        (start: "68500", meso: Mesoregion(code: "1505", name: "Sudeste Paraense", stateCode: "15", stateName: "Para", region: "Norte")),
        (start: "68700", meso: Mesoregion(code: "1501", name: "Baixo Amazonas", stateCode: "15", stateName: "Para", region: "Norte")),
        (start: "68900", meso: Mesoregion(code: "1601", name: "Norte do Amapa", stateCode: "16", stateName: "Amapa", region: "Norte")),
        (start: "68950", meso: Mesoregion(code: "1602", name: "Sul do Amapa", stateCode: "16", stateName: "Amapa", region: "Norte")),
        (start: "69000", meso: Mesoregion(code: "1301", name: "Norte Amazonense", stateCode: "13", stateName: "Amazonas", region: "Norte")),
        (start: "69100", meso: Mesoregion(code: "1302", name: "Sudoeste Amazonense", stateCode: "13", stateName: "Amazonas", region: "Norte")),
        (start: "69300", meso: Mesoregion(code: "1303", name: "Centro Amazonense", stateCode: "13", stateName: "Amazonas", region: "Norte")),
        (start: "69400", meso: Mesoregion(code: "1304", name: "Sul Amazonense", stateCode: "13", stateName: "Amazonas", region: "Norte")),
        (start: "69800", meso: Mesoregion(code: "1401", name: "Norte de Roraima", stateCode: "14", stateName: "Roraima", region: "Norte")),
        (start: "69900", meso: Mesoregion(code: "1101", name: "Leste Rondoniense", stateCode: "11", stateName: "Rondonia", region: "Norte")),
        (start: "69920", meso: Mesoregion(code: "1201", name: "Vale do Jurua", stateCode: "12", stateName: "Acre", region: "Norte")),
        (start: "69950", meso: Mesoregion(code: "1202", name: "Vale do Acre", stateCode: "12", stateName: "Acre", region: "Norte")),
        (start: "69980", meso: Mesoregion(code: "1102", name: "Madeira-Guapore", stateCode: "11", stateName: "Rondonia", region: "Norte")),
        (start: "70000", meso: Mesoregion(code: "5300", name: "Distrito Federal", stateCode: "53", stateName: "Distrito Federal", region: "Centro-Oeste")),
        (start: "71000", meso: Mesoregion(code: "5300", name: "Distrito Federal", stateCode: "53", stateName: "Distrito Federal", region: "Centro-Oeste")),
        (start: "72000", meso: Mesoregion(code: "5300", name: "Distrito Federal", stateCode: "53", stateName: "Distrito Federal", region: "Centro-Oeste")),
        (start: "72800", meso: Mesoregion(code: "5201", name: "Noroeste Goiano", stateCode: "52", stateName: "Goias", region: "Centro-Oeste")),
        (start: "73000", meso: Mesoregion(code: "5202", name: "Norte Goiano", stateCode: "52", stateName: "Goias", region: "Centro-Oeste")),
        (start: "73700", meso: Mesoregion(code: "5205", name: "Centro Goiano", stateCode: "52", stateName: "Goias", region: "Centro-Oeste")),
        (start: "74000", meso: Mesoregion(code: "5205", name: "Centro Goiano", stateCode: "52", stateName: "Goias", region: "Centro-Oeste")),
        (start: "75000", meso: Mesoregion(code: "5203", name: "Leste Goiano", stateCode: "52", stateName: "Goias", region: "Centro-Oeste")),
        (start: "75500", meso: Mesoregion(code: "5204", name: "Sul Goiano", stateCode: "52", stateName: "Goias", region: "Centro-Oeste")),
        (start: "76000", meso: Mesoregion(code: "5204", name: "Sul Goiano", stateCode: "52", stateName: "Goias", region: "Centro-Oeste")),
        (start: "76300", meso: Mesoregion(code: "5201", name: "Noroeste Goiano", stateCode: "52", stateName: "Goias", region: "Centro-Oeste")),
        (start: "76400", meso: Mesoregion(code: "5204", name: "Sul Goiano", stateCode: "52", stateName: "Goias", region: "Centro-Oeste")),
        (start: "76600", meso: Mesoregion(code: "5205", name: "Centro Goiano", stateCode: "52", stateName: "Goias", region: "Centro-Oeste")),
        (start: "76800", meso: Mesoregion(code: "1701", name: "Ocidental do Tocantins", stateCode: "17", stateName: "Tocantins", region: "Norte")),
        (start: "77000", meso: Mesoregion(code: "1702", name: "Oriental do Tocantins", stateCode: "17", stateName: "Tocantins", region: "Norte")),
        (start: "77300", meso: Mesoregion(code: "1701", name: "Ocidental do Tocantins", stateCode: "17", stateName: "Tocantins", region: "Norte")),
        (start: "77500", meso: Mesoregion(code: "1702", name: "Oriental do Tocantins", stateCode: "17", stateName: "Tocantins", region: "Norte")),
        (start: "77800", meso: Mesoregion(code: "1701", name: "Ocidental do Tocantins", stateCode: "17", stateName: "Tocantins", region: "Norte")),
        (start: "78000", meso: Mesoregion(code: "5101", name: "Norte Mato-Grossense", stateCode: "51", stateName: "Mato Grosso", region: "Centro-Oeste")),
        (start: "78100", meso: Mesoregion(code: "5102", name: "Nordeste Mato-Grossense", stateCode: "51", stateName: "Mato Grosso", region: "Centro-Oeste")),
        (start: "78200", meso: Mesoregion(code: "5103", name: "Sudoeste Mato-Grossense", stateCode: "51", stateName: "Mato Grosso", region: "Centro-Oeste")),
        (start: "78500", meso: Mesoregion(code: "5104", name: "Centro-Sul Mato-Grossense", stateCode: "51", stateName: "Mato Grosso", region: "Centro-Oeste")),
        (start: "78700", meso: Mesoregion(code: "5104", name: "Centro-Sul Mato-Grossense", stateCode: "51", stateName: "Mato Grosso", region: "Centro-Oeste")),
        (start: "78800", meso: Mesoregion(code: "5105", name: "Sudeste Mato-Grossense", stateCode: "51", stateName: "Mato Grosso", region: "Centro-Oeste")),
        (start: "79000", meso: Mesoregion(code: "5004", name: "Pantanais Sul Mato-Grossenses", stateCode: "50", stateName: "Mato Grosso do Sul", region: "Centro-Oeste")),
        (start: "79100", meso: Mesoregion(code: "5001", name: "Centro Norte de Mato Grosso do Sul", stateCode: "50", stateName: "Mato Grosso do Sul", region: "Centro-Oeste")),
        (start: "79300", meso: Mesoregion(code: "5002", name: "Leste de Mato Grosso do Sul", stateCode: "50", stateName: "Mato Grosso do Sul", region: "Centro-Oeste")),
        (start: "79500", meso: Mesoregion(code: "5003", name: "Sudoeste de Mato Grosso do Sul", stateCode: "50", stateName: "Mato Grosso do Sul", region: "Centro-Oeste")),
        (start: "79800", meso: Mesoregion(code: "5004", name: "Pantanais Sul Mato-Grossenses", stateCode: "50", stateName: "Mato Grosso do Sul", region: "Centro-Oeste")),
        (start: "80000", meso: Mesoregion(code: "4106", name: "Metropolitana de Curitiba", stateCode: "41", stateName: "Parana", region: "Sul")),
        (start: "81000", meso: Mesoregion(code: "4106", name: "Metropolitana de Curitiba", stateCode: "41", stateName: "Parana", region: "Sul")),
        (start: "82000", meso: Mesoregion(code: "4106", name: "Metropolitana de Curitiba", stateCode: "41", stateName: "Parana", region: "Sul")),
        (start: "83000", meso: Mesoregion(code: "4106", name: "Metropolitana de Curitiba", stateCode: "41", stateName: "Parana", region: "Sul")),
        (start: "83200", meso: Mesoregion(code: "4101", name: "Noroeste Paranaense", stateCode: "41", stateName: "Parana", region: "Sul")),
        (start: "84000", meso: Mesoregion(code: "4102", name: "Centro Ocidental Paranaense", stateCode: "41", stateName: "Parana", region: "Sul")),
        (start: "84200", meso: Mesoregion(code: "4103", name: "Norte Central Paranaense", stateCode: "41", stateName: "Parana", region: "Sul")),
        (start: "85000", meso: Mesoregion(code: "4104", name: "Norte Pioneiro Paranaense", stateCode: "41", stateName: "Parana", region: "Sul")),
        (start: "85500", meso: Mesoregion(code: "4105", name: "Centro Oriental Paranaense", stateCode: "41", stateName: "Parana", region: "Sul")),
        (start: "85800", meso: Mesoregion(code: "4107", name: "Oeste Paranaense", stateCode: "41", stateName: "Parana", region: "Sul")),
        (start: "85900", meso: Mesoregion(code: "4108", name: "Sudoeste Paranaense", stateCode: "41", stateName: "Parana", region: "Sul")),
        (start: "86000", meso: Mesoregion(code: "4103", name: "Norte Central Paranaense", stateCode: "41", stateName: "Parana", region: "Sul")),
        (start: "86400", meso: Mesoregion(code: "4101", name: "Noroeste Paranaense", stateCode: "41", stateName: "Parana", region: "Sul")),
        (start: "86600", meso: Mesoregion(code: "4103", name: "Norte Central Paranaense", stateCode: "41", stateName: "Parana", region: "Sul")),
        (start: "87000", meso: Mesoregion(code: "4101", name: "Noroeste Paranaense", stateCode: "41", stateName: "Parana", region: "Sul")),
        (start: "87300", meso: Mesoregion(code: "4102", name: "Centro Ocidental Paranaense", stateCode: "41", stateName: "Parana", region: "Sul")),
        (start: "87500", meso: Mesoregion(code: "4107", name: "Oeste Paranaense", stateCode: "41", stateName: "Parana", region: "Sul")),
        (start: "87700", meso: Mesoregion(code: "4101", name: "Noroeste Paranaense", stateCode: "41", stateName: "Parana", region: "Sul")),
        (start: "88000", meso: Mesoregion(code: "4205", name: "Grande Florianopolis", stateCode: "42", stateName: "Santa Catarina", region: "Sul")),
        (start: "88100", meso: Mesoregion(code: "4206", name: "Sul Catarinense", stateCode: "42", stateName: "Santa Catarina", region: "Sul")),
        (start: "88300", meso: Mesoregion(code: "4204", name: "Vale do Itajai", stateCode: "42", stateName: "Santa Catarina", region: "Sul")),
        (start: "88500", meso: Mesoregion(code: "4206", name: "Sul Catarinense", stateCode: "42", stateName: "Santa Catarina", region: "Sul")),
        (start: "88700", meso: Mesoregion(code: "4206", name: "Sul Catarinense", stateCode: "42", stateName: "Santa Catarina", region: "Sul")),
        (start: "88900", meso: Mesoregion(code: "4201", name: "Oeste Catarinense", stateCode: "42", stateName: "Santa Catarina", region: "Sul")),
        (start: "89000", meso: Mesoregion(code: "4204", name: "Vale do Itajai", stateCode: "42", stateName: "Santa Catarina", region: "Sul")),
        (start: "89100", meso: Mesoregion(code: "4203", name: "Norte Catarinense", stateCode: "42", stateName: "Santa Catarina", region: "Sul")),
        (start: "89200", meso: Mesoregion(code: "4203", name: "Norte Catarinense", stateCode: "42", stateName: "Santa Catarina", region: "Sul")),
        (start: "89300", meso: Mesoregion(code: "4201", name: "Oeste Catarinense", stateCode: "42", stateName: "Santa Catarina", region: "Sul")),
        (start: "89400", meso: Mesoregion(code: "4203", name: "Norte Catarinense", stateCode: "42", stateName: "Santa Catarina", region: "Sul")),
        (start: "89500", meso: Mesoregion(code: "4201", name: "Oeste Catarinense", stateCode: "42", stateName: "Santa Catarina", region: "Sul")),
        (start: "89600", meso: Mesoregion(code: "4201", name: "Oeste Catarinense", stateCode: "42", stateName: "Santa Catarina", region: "Sul")),
        (start: "89700", meso: Mesoregion(code: "4202", name: "Serrana", stateCode: "42", stateName: "Santa Catarina", region: "Sul")),
        (start: "89800", meso: Mesoregion(code: "4201", name: "Oeste Catarinense", stateCode: "42", stateName: "Santa Catarina", region: "Sul")),
        (start: "90000", meso: Mesoregion(code: "4314", name: "Metropolitana de Porto Alegre", stateCode: "43", stateName: "Rio Grande do Sul", region: "Sul")),
        (start: "91000", meso: Mesoregion(code: "4314", name: "Metropolitana de Porto Alegre", stateCode: "43", stateName: "Rio Grande do Sul", region: "Sul")),
        (start: "92000", meso: Mesoregion(code: "4314", name: "Metropolitana de Porto Alegre", stateCode: "43", stateName: "Rio Grande do Sul", region: "Sul")),
        (start: "93000", meso: Mesoregion(code: "4314", name: "Metropolitana de Porto Alegre", stateCode: "43", stateName: "Rio Grande do Sul", region: "Sul")),
        (start: "94000", meso: Mesoregion(code: "4314", name: "Metropolitana de Porto Alegre", stateCode: "43", stateName: "Rio Grande do Sul", region: "Sul")),
        (start: "95000", meso: Mesoregion(code: "4307", name: "Nordeste Rio-Grandense", stateCode: "43", stateName: "Rio Grande do Sul", region: "Sul")),
        (start: "95500", meso: Mesoregion(code: "4308", name: "Noroeste Rio-Grandense", stateCode: "43", stateName: "Rio Grande do Sul", region: "Sul")),
        (start: "96000", meso: Mesoregion(code: "4312", name: "Sudoeste Rio-Grandense", stateCode: "43", stateName: "Rio Grande do Sul", region: "Sul")),
        (start: "96200", meso: Mesoregion(code: "4310", name: "Centro Ocidental Rio-Grandense", stateCode: "43", stateName: "Rio Grande do Sul", region: "Sul")),
        (start: "96400", meso: Mesoregion(code: "4312", name: "Sudoeste Rio-Grandense", stateCode: "43", stateName: "Rio Grande do Sul", region: "Sul")),
        (start: "96600", meso: Mesoregion(code: "4311", name: "Centro Oriental Rio-Grandense", stateCode: "43", stateName: "Rio Grande do Sul", region: "Sul")),
        (start: "96800", meso: Mesoregion(code: "4309", name: "Sudeste Rio-Grandense", stateCode: "43", stateName: "Rio Grande do Sul", region: "Sul")),
        (start: "97000", meso: Mesoregion(code: "4310", name: "Centro Ocidental Rio-Grandense", stateCode: "43", stateName: "Rio Grande do Sul", region: "Sul")),
        (start: "97100", meso: Mesoregion(code: "4308", name: "Noroeste Rio-Grandense", stateCode: "43", stateName: "Rio Grande do Sul", region: "Sul")),
        (start: "97300", meso: Mesoregion(code: "4310", name: "Centro Ocidental Rio-Grandense", stateCode: "43", stateName: "Rio Grande do Sul", region: "Sul")),
        (start: "97500", meso: Mesoregion(code: "4308", name: "Noroeste Rio-Grandense", stateCode: "43", stateName: "Rio Grande do Sul", region: "Sul")),
        (start: "97800", meso: Mesoregion(code: "4308", name: "Noroeste Rio-Grandense", stateCode: "43", stateName: "Rio Grande do Sul", region: "Sul")),
        (start: "98000", meso: Mesoregion(code: "4308", name: "Noroeste Rio-Grandense", stateCode: "43", stateName: "Rio Grande do Sul", region: "Sul")),
        (start: "98500", meso: Mesoregion(code: "4308", name: "Noroeste Rio-Grandense", stateCode: "43", stateName: "Rio Grande do Sul", region: "Sul")),
        (start: "98700", meso: Mesoregion(code: "4308", name: "Noroeste Rio-Grandense", stateCode: "43", stateName: "Rio Grande do Sul", region: "Sul")),
        (start: "98800", meso: Mesoregion(code: "4308", name: "Noroeste Rio-Grandense", stateCode: "43", stateName: "Rio Grande do Sul", region: "Sul")),
        (start: "99000", meso: Mesoregion(code: "4307", name: "Nordeste Rio-Grandense", stateCode: "43", stateName: "Rio Grande do Sul", region: "Sul")),
        (start: "99100", meso: Mesoregion(code: "4307", name: "Nordeste Rio-Grandense", stateCode: "43", stateName: "Rio Grande do Sul", region: "Sul")),
        (start: "99300", meso: Mesoregion(code: "4308", name: "Noroeste Rio-Grandense", stateCode: "43", stateName: "Rio Grande do Sul", region: "Sul")),
        (start: "99500", meso: Mesoregion(code: "4311", name: "Centro Oriental Rio-Grandense", stateCode: "43", stateName: "Rio Grande do Sul", region: "Sul")),
        (start: "99700", meso: Mesoregion(code: "4308", name: "Noroeste Rio-Grandense", stateCode: "43", stateName: "Rio Grande do Sul", region: "Sul")),
    ]
}
